gigachat:
  auth-key: MTM3YTUzYTEtNDMzMi00ZDMyLThhZjMtN2Y0MWZhOGNhNmQxOmY1YzkwNTkzLWI5N2EtNDhiYy04OGQ5LTQ0ZDFkMDNkMzk4MQ==
  client-id: 137a53a1-4332-4d32-8af3-7f41fa8ca6d1
  client-secret: f5c90593-b97a-48bc-88d9-44d1d03d3981